### ISSUE TITLE
Trouble with Display Quality on Waveshare Rev 2.2 ePaper HAT

### ISSUE THREAD

**Issue by Erechtheus** [lmarzen/esp32-weather-epd#103]
Hi! I attempted to build your project using a Waveshare Rev 2.2 ePaper HAT. However, I'm encountering an issue with the display. The upper part of the screen appears clear, but the lower half is very difficult to read. Could this indicate that the display is broken? Is there a way to validate or troubleshoot this issue? Thank you!

![PXL_20240527_201927977](https://github.com/lmarzen/esp32-weather-epd/assets/3033565/ea06ae8f-1590-4b0b-9187-d66b6eb0c2f2)

**Comment by Erechtheus** [comment]
Can confirm that the error was due to a broken display. I also switched from ePaper HAT to DESPI.

**Comment by lmarzen** [comment]
Sorry to hear that, but Im glad you were able to diagnose the issue.
