### ISSUE TITLE
Problem with Waveshare Display only updating half of the screen

### ISSUE THREAD

**Issue by Juliiiian** [lmarzen/esp32-weather-epd#105]
I updated the esp since the NTP server wasn't really working, the version before was close to a year old (130 commits behind). It works flawless on my other one but on this one I thought an update might fix it, but now I tested both drivers and I always update only the bottom half of the screen, like some sort of offset. But when the updating happens, it all goes black around the display and the bottom half. Just the middle upper part doesn't change. 

I don't think the display is broken, since before updating to a newer version it set the NTP error and the display worked.

Probably just an easy fix, but I triple checked every pin and it should work.

![IMG20240605185030](https://github.com/lmarzen/esp32-weather-epd/assets/89937721/56384bfd-9b7a-4af4-aa38-5f194d0ba412)

**Comment by lmarzen** [comment]
Sorry for the delayed response. Were you able to get this resolved? I'm not sure qhat might be causing this, I haven't seen this one before.

**Comment by Juliiiian** [comment]
I honestly don't know what the issue was, I downgraded to a version from 2023 Oktober or so and it worked. But there were some cable contacts not working, I soldered them back together and now it works. I think it was an issue on my end
