### ISSUE TITLE
WaveShare 7.5 deadzone on the right

### ISSUE THREAD

**Issue by RedlingerBenjamin** [lmarzen/esp32-weather-epd#107]
small strip on the right wont show any image,
do i have a faulty screen or is it a issue with my setup 
![IMG_0298](https://github.com/lmarzen/esp32-weather-epd/assets/31820383/cabacc55-9a38-4408-83e4-ffcff6e67268)

**Comment by lmarzen** [comment]
Haven't seen this one before. I suspect it may be a defective panel.
