### ISSUE TITLE
Housing

### ISSUE THREAD

**Issue by MPHarms** [lmarzen/esp32-weather-epd#108]
Hello Imarzen
I find your project very intersting and build it now and thanks for implementing the language "German".
I could not find any good housing and so I designed my own with ThinkerCAD.
Maybe someone other would like it to.
If you want you can add it to the list of housings.
You can find the description and the .stl files here:
https://www.thingiverse.com/thing:6666148
In the next days I want to add some real photos.
Greetings
MPHarms

**Comment by lmarzen** [comment]
Hi @MPHarms,

I'm glad you like the project, thanks for the kind words! Great housing design, good work! I've added a link to your design in the readme.
