### ISSUE TITLE
how to find low battery check?

### ISSUE THREAD

**Issue by PaekHyun** [lmarzen/esp32-weather-epd#113]
It seems that the status of the battery is being checked using esp32's ADC.
However, I understand that esp32's ADC can receive input up to 3.3V.
The 18650 battery is known to have 4.2V when fully charged.
But I wonder how I can check the status of the battery.

**Comment by lmarzen** [comment]
The firebeetle 2 esp32-e board recommended for this project uses a 1M+1M voltage divider (which divides the voltage in half) between the 4.2v lipo battery connector and the adc pin it is connected to.  In the code, I adjust for this by multiplying the measured voltage by 2 to get the actual battery voltage.

https://docs.espressif.com/projects/esp-idf/en/v4.4/esp32/api-reference/peripherals/adc.html#adc-attenuation

Using an attenuation of 11db with the voltage divider on the firebeetle board gives an effective measurable voltage of 0.3v-4.9v.
