### ISSUE TITLE
Wrong Boot mode detected

### ISSUE THREAD

**Issue by Silverflo2030** [lmarzen/esp32-weather-epd#126]
Unfortunately, I always get the following error message. I've already tried it with a working weather station. Unfortunately, I can't get any transmission. Does anyone know what the problem is? 

A fatal error occurred: Failed to connect to ESP32: Wrong boot mode detected (0x13)! The chip needs to be in download mode.
For troubleshooting steps visit: https://docs.espressif.com/projects/esptool/en/latest/troubleshooting.html
*** [upload] Error 2
==================================================== [FAILED] Took 24.95 seconds ====================================================

Environment                 Status    Duration
--------------------------  --------  ------------
dfrobot_firebeetle2_esp32e  FAILED    00:00:24.947
=============================================== 1 failed, 0 succeeded in 00:00:24.947 ===============================================

 *  The terminal process "C:\Users\benutzer\.platformio\penv\Scripts\platformio.exe 'run', '--target', 'upload'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it

**Comment by lmarzen** [comment]
This is not an issue with this project specifically. As the error message says, "For troubleshooting steps visit: https://docs.espressif.com/projects/esptool/en/latest/troubleshooting.html".

I recommend first disconnecting everything from the esp32 and just trying to flash it with the USB connected.
As the troubleshooting page links [here](https://docs.espressif.com/projects/esptool/en/latest/esp32/advanced-topics/boot-mode-selection.html) for info about the boot mode selection and if you have connected some pins in a certain way you may be preventing the esp32 from being reset into the download mode automatically. If this doesn't work, try other things recommended on the troubleshooting page.
