### ISSUE TITLE
One call API Upgrade 2.5 to 3.0

### ISSUE THREAD

**Issue by Ianszh** [lmarzen/esp32-weather-epd#129]
Hello Luke,

Thanks again for the great project, it's been running fine for ages but now though I see that the 2.5 APi has been deprecated.

I've created a new 3.0 subscription and limited it to 1000 call per day, I take it I'll have to reinstall the whole project to change the API call?

Thanks Ian

**Comment by lmarzen** [comment]
Yes, you are correct.

**Comment by lmarzen** [comment]
I think in theory it may be possible, though it would be non-trivial and highly technical. Unfortunately, you'll have to start clean, unless you can find your old files.

Side note, I am slowly working on a web interface for this project in the background, which would not require a reflash to update settings. Hopefully, one day, eliminating some of the user-friendliness issues.

**Comment by Ianszh** [comment]
I thought so, I'll try and find the old file or start again.

That would be cool, I see a few other projects going / gone that way.

**Comment by lmarzen** [comment]
godspeed
