### ISSUE TITLE
Waveshare 7.5in (B) 

### ISSUE THREAD

**Issue by zorel** [lmarzen/esp32-weather-epd#13]
Hello.

I'm trying to use a https://www.waveshare.com/wiki/7.5inch_e-Paper_HAT_(B) with the project.
I put in renderer.cpp:
```
// B/W display
// GxEPD2_BW<GxEPD2_750_T7, GxEPD2_750_T7::HEIGHT> display(
//   GxEPD2_750_T7(PIN_EPD_CS,
//                 PIN_EPD_DC,
//                 PIN_EPD_RST,
//                 PIN_EPD_BUSY));
// 3-colour displays */
GxEPD2_3C<GxEPD2_750c_Z08, GxEPD2_750c_Z08::HEIGHT> display(
  GxEPD2_750c_Z08(PIN_EPD_CS,
             PIN_EPD_DC,
             PIN_EPD_RST,
             PIN_EPD_BUSY));
```

And changed renderer.h and includes accordingly. I used the _Z08 because of the resolution of 800x480.

I have this error at linkage:
```
Linking .pio\build\firebeetle32\firmware.elf
c:/users/aurel/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\firebeetle32\firmware.elf section `.dram0.bss' will not fit in region `dram0_0_seg'
c:/users/aurel/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: DRAM segment data does not fit.
c:/users/aurel/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: DRAM segment data does not fit.
c:/users/aurel/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: region `dram0_0_seg' overflowed by 23880 bytes
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\firebeetle32\firmware.elf] Error 1
```

Do you know if that panel can be used, or the way it can be?

**Comment by lmarzen** [comment]
Hi @zorel. I was just now able to recreate your issue. Looks like the project is just slightly too large when using the 3c display. Let me work on this and get back to you. I think others might be interested in using the same display you are, and I would like to support it.

**Comment by lmarzen** [comment]
@zorel, I made some changes in a branch https://github.com/lmarzen/esp32-weather-epd/tree/3c-test. The code compiles now for the 7.5in 3c epd. I have not had a chance to test these changes yet, but once I do, I will merge them into main. I also added a macro to renderer.h to easily select between the B/W and 3-color panels.

**Comment by zorel** [comment]
Seems to work fine for now, the refresh is ok. I will let the thing run for few hours. Thanks.

**Comment by lmarzen** [comment]
You're welcome, I have merged the changes into main.
