### ISSUE TITLE
Combine ESP and BMP280-Sensor on Feather ESP32-S2 

### ISSUE THREAD

**Issue by JO70** [lmarzen/esp32-weather-epd#16]
Adding the Feather ESP32-S2 may be considered for more compact models.
[https://botland.de/img/art/inne/20785_5.jpg](https://botland.de/img/art/inne/20785_5.jpg)
[https://learn.adafruit.com/adafruit-esp32-s2-feather/overview](url)
Regards JO70

**Comment by lmarzen** [comment]
Hi JO70,
Using the Feather ESP32-S2 for this project should be relatively simple. You need to edit the platform.ini file to change the board to the Feather ESP32-S2. Then go to config.cpp and update your pinout.
Let me know if you have any other questions.
