### ISSUE TITLE
api_response.h

### ISSUE THREAD

**Issue by MonsterThews** [lmarzen/esp32-weather-epd#18]
Where is api_response.h?

Starting to build your weather station, but Platformio can't find this library.

**Comment by lmarzen** [comment]
It is in platformio/include. Did you open the folder entitled 'platformio' with vscode?

**Comment by MonsterThews** [comment]
It's not in the .ini file.Ah- /include.
Thank you
    On Monday, March 6, 2023 at 02:59:19 PM EST, Luke Marzen ***@***.***> wrote:  
 
 


It is in platformio/include. Did you open the folder entitled 'platformio' with vscode?

**Comment by lmarzen** [comment]
You're right, it's not in platform.ini. It isn't necessary to specify because include is the default. see https://docs.platformio.org/en/latest/projectconf/sections/platformio/options/directory/include_dir.html
