### ISSUE TITLE
Error redrerer.cpp

### ISSUE THREAD

**Issue by Dozentz** [lmarzen/esp32-weather-epd#2]
When loading into the ESP, an error occurs in the line
src/renderer.cpp:317:59: error: no matching function for call to 'max(float, double)'

317: uint uvi = static_cast<uint>(max(round(current.uvi), 0.0));

*** [.pio\build\firebeetle32\src\renderer.cpp.o] Error 1

**Comment by lmarzen** [comment]
Thanks, I guess the compiler decided it now had a problem with that. Should be fixed now.
