### ISSUE TITLE
Localisation: AQI

### ISSUE THREAD

**Issue by jrial** [lmarzen/esp32-weather-epd#24]
I've created a Dutch translation (for which I'll create a pull request once I figure out some last details), but I noticed the air quality index is reported in English. Not sure if that issue belongs here, or in the pollutant-concentration-to-aqi repo, since the strings are taken directly from there. But since the AQI repo doesn't have any translations, I felt the correct place to create an issue was here.

It would be nice if these strings would also be translatable via the translation files.

**Comment by lmarzen** [comment]
Hi Jrial, this is something that I have been meaning to take care of for a while, but I have continued to push it off. Should be relatively quick to do. I am hoping to get to it later this week.
-Luke
