### ISSUE TITLE
Waveshare e-Paper Driver HAT rev2.3

### ISSUE THREAD

**Issue by Spanholz** [lmarzen/esp32-weather-epd#42]
I got a new 7.5 3-colour display from Waveshare this week including a Waveshare e-Paper Driver HAT rev2.3. The new HAT is not documented on Waveshares webpage yet and is different from the previous versions. It features 9 pins, with an additional PWR pin. The display does not start with VCC or PWR only connected. But with PWR connected to second 3.3V and therefore disconnecting the BME it works. I will update if the PWR pin can be put on same 3V3 as the VCC from the hat. 

![e-Paper HAT](https://github.com/lmarzen/esp32-weather-epd/assets/25983258/357adbbd-079e-497f-b842-8a5b27ab1045)

**Comment by Spanholz** [comment]
Putting PWR and VCC on the same 3V3 pin works. The other PIN can than be used by BME

**Comment by lmarzen** [comment]
Thanks for investigating and documenting this.

I just found this page talking about the changes...
https://www.waveshare.net/wiki/E-Paper_Driver_HAT

Translating to english...

> Version changes:
> 
>     The RST pin now only controls reset and no longer controls power on and off.
>     Add a PWR pin to control power on and off
>     Replace the inductor with a smaller, thinner package
>     PH2.0 8Pin interface replaced with GH1.25 9Pin interface
>     The version number silk screen is updated to Rev2.3
> 
>     If you need to upgrade to this version from a previous version, you can choose one of the following methods for compatibility:
> 
>     Update the program to the latest (Arduino program only supports 7.5inch e-Paper, 7.5inch e-Paper (B), 5.83inch e-Paper, 5.83inch e-Paper (B), 2.9inch e-Paper (D), 2.13 inch e-Paper (D) six screens)
>     Connect PWR pin to 3.3V
>     Solder a 47K (or similar) resistor to the empty pad on the back

Appears you are right to connect PWR to 3.3V. I'll keep an eye on the epaper driver library this project uses and see if they provide any updates.

**Comment by nonpayer** [comment]
I apologize, but I'm a beginner. I also received the Waveshare e-Paper Driver HAT rev2.3. I'm doing something wrong, because when I upload, I have 141 problems in renderer.app. Can anyone help me as a complete beginner? I followed the instructions, but I probably have something wrongly connected because I have HAT rev 2.3. and there is another in the manual...
<img width="579" alt="image" src="https://github.com/lmarzen/esp32-weather-epd/assets/146516851/213bba86-dca7-4693-945b-f5725b8e3d5e">


<img width="629" alt="image" src="https://github.com/lmarzen/esp32-weather-epd/assets/146516851/ddd41555-ada9-47a0-9aeb-28673f0dff53">

**Comment by lmarzen** [comment]
If you are getting a lot of problems in renderer.cpp, your config.h file may be misconfigured.

**Comment by lmarzen** [comment]
Additionally can you share the exact model of panel you are using as well as the model of esp32 to make it easier to assist in troubleshooting.

**Comment by nonpayer** [comment]
800×480, 7.5inch E-Ink display HAT for Raspberry Pi and e-Paper Driver HAT ver 2.3 with 9 pins, with an additional PWR pin.

FireBeetle 2 ESP32-E

Update is success without error, but i have only black edges on the display...

**Comment by lmarzen** [comment]
Try reverting your config.h back to the default.

**Comment by nonpayer** [comment]
Thanks for advice. I tried to use the default config.h and the upload was successful. But I have a 9-pin HAT and with an additional PWR pin. As Spanholz already wrote, the display only works with PWR connected to second 3.3V and therefore disconnecting the BME, or PWR and VCC on the same 3V3. But how do I plug PWR and 3V3 into the same connector. ?

**Comment by lmarzen** [comment]
You will need to make a splitter. or solder both wires to the same 3v on the esp32

**Comment by sonett12** [comment]
first of all thank you very much for your project @lmarzen I got myself the same hardware and have it running a few days now, works like a charm :-)

I also got the rev2.3 e-paper hat with this additional pwr pin to enable the display. I looked it up in the schematic here
https://files.waveshare.com/upload/8/8e/E-Paper_Driver_HAT.pdf 

<img width="384" alt="Bildschirmfoto 2023-10-03 um 07 34 49" src="https://github.com/lmarzen/esp32-weather-epd/assets/146804966/11363024-ac60-48ae-bafa-2e844b83f07d">

For my understanding the additional pin can be controlled to activate/disable the display but is not powering the display, so I just used a GPIO pin for this, I connected the pwr pin to D6 pin 14 and added the activation in the main.ccp as such (lines 318..320 + 335):

<img width="614" alt="Bildschirmfoto 2023-10-03 um 07 32 33" src="https://github.com/lmarzen/esp32-weather-epd/assets/146804966/61ba94ed-9151-4dbf-9575-aeb2bd0ef38e">

for me that was enough, maybe others you can do so as well. Could be nice to have it an option in the project source code to configure this pwr pin as well.

**Comment by nonpayer** [comment]
> You will need to make a splitter. or solder both wires to the same 3v on the esp32

I did it and everything works fine. Thanks for help.

**Comment by lmarzen** [comment]
@sonett12 Thanks for investigating this further and sharing your results. I'll be adding an option for this and adding some documentation when I get a chance.

**Comment by Marckau** [comment]
I tried the @sonett12 code and hooked the power pin to the D6 and updated the code as well as just soldering both the VCC and PWR on the 3V3 line. Same result the screen works and displays all the correct information for a brief moment then goes black. Any idea why? I have the black and red display. 
![2](https://github.com/lmarzen/esp32-weather-epd/assets/147877362/9777916b-f644-444f-b0c4-d721c98f1ab0)
![1](https://github.com/lmarzen/esp32-weather-epd/assets/147877362/97a25485-a6d8-40a5-bbc8-2b2e7e8a2711)

**Comment by lmarzen** [comment]
I have suggested users purchase the DESPI-CO2 adaptor board instead of the waveshare hat going forward.

**Comment by nicoh88** [comment]
> the pwr pin to D6 pin 14

Hi @sonett12, you say you would use the **D6 / 14** for the new e-Paper HAT rev2.3 for the additional **PIN PWR**.

According to the [wiring diagram](https://github.com/lmarzen/esp32-weather-epd/blob/main/showcase/wiring_diagram_waveshare_rev22.png) from lmarzen, **D6 / 14** is already used for **BUSY**. **Do you then not use BUSY at all or how did you do it?**

I actually wanted to use **D9 / 2** for PWR, but according to the documentation of the[ FireBeetle Board ESP32-E (SKU DFR0654)](https://wiki.dfrobot.com/FireBeetle_Board_ESP32_E_SKU_DFR0654) D9 / 2 has a remark: "_For controlling onboard LED by outputting digital signal_"

Hence my question about what you did with BUSY.
Thank you in advance for your answer.
