### ISSUE TITLE
Display shows 0 for all all fields (OWM onecall v2.5 not available to new users)

### ISSUE THREAD

**Issue by lmarzen** [lmarzen/esp32-weather-epd#5]
![UGc-Bg78](https://user-images.githubusercontent.com/10892971/213255685-140de1bc-2f90-4b60-b3bd-bdfa490ab651.jpeg)

_Originally posted by @Dozentz in https://github.com/lmarzen/esp32-weather-epd/issues/3#issuecomment-1387348544_

**Comment by lmarzen** [comment]
Great, thanks. I will see if I can reproduce your issue later today if I have time.

**Comment by lmarzen** [comment]
Hmmm, I tried on my esp32, setting the lat and long you provided, and it worked just fine for me. This is definitely a weird issue.

**Comment by Dozentz** [comment]
Maybe a problem with the api request. I checked the key with the request in the browser everything is ok. How else can you find out what kind of request is obtained in the esp32 itself. Date, time are synchronized via ntp server, the rest is zero

**Comment by lmarzen** [comment]
Well the request is made in getOWMonecall() in src/client_utils.cpp. You could add a print message after line 120 in client_utils.cpp, then it will print the uri used to make the request to the serial monitor.
`Serial.println(uri);`
I think maybe this could be an issue with how I am using ArduinoJson (the library used to parse the api response). But it appears the request is good, otherwise, you would get an error message at the bottom of the display indicating that the esp32 received and HTTP code other than 200(OK).

**Comment by lmarzen** [comment]
I found some things we could try on https://arduinojson.org/v6/issues/incomplete-output/.

It first suggests... "That’s because the JsonDocument is too small: it doesn’t have enough room to store the complete tree.
You can quickly diagnose this issue by looking at the result of JsonDocument::overflowed(). If it’s true, then the JsonDocument was too small, so it had to drop some values."

So try adding the following to src/api_response.cpp at line 224:
`  Serial.print("filter.overflowed =");`
`  Serial.println(filter.overflowed());`
`  Serial.print("doc.overflowed =");`
`  Serial.println(doc.overflowed());`

Then send your serial monitor output.

**Comment by Dozentz** [comment]
`Thursday, January 19, 2023 19:30:16
OpenWeatherMap One Call API connection error: 401
OpenWeatherMap One Call API connection error: 401
OpenWeatherMap One Call API connection error: 401
24.22
27.23
Busy Timeout!
_PowerOn : 10001215
Busy Timeout!
_Update_Full : 10001100
Busy Timeout!
_PowerOff : 10001092
Min Free Heap: 138475
Status:
Awake for 35.479s
Deep-sleep for 1764s`

**Comment by lmarzen** [comment]
401 is unauthorized, meaning an incorrect API key.

**Comment by lmarzen** [comment]
Try making this request in your browser. Is it successful? http://api.openweathermap.org/data/2.5/onecall?lat=40.7128&lon=-74.0060&units=imperial&lang=en&appid=YOUR_API_KEY_HERE

**Comment by lmarzen** [comment]
I found this issue... https://github.com/domoticz/domoticz/issues/5336

**Comment by Dozentz** [comment]
`{"cod":401, "message": "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."}`
The account registered in December 2022

**Comment by lmarzen** [comment]
Well, that's no good :/ no wonder it is showing 0's for everything. I'm not to sure what to do about this. I guess I might need to make some changes so that it doesn't use the onecall api anymore. That may take some work. Not sure when I will get around to doing that, but I will keep you updated.

**Comment by Dozentz** [comment]
Good. Thank you for the feedback

**Comment by lmarzen** [comment]
Another group of people discussing the issue: https://wordpress.org/support/topic/401-api-error-in-owm-weather/page/2/

**Comment by lmarzen** [comment]
I think I have decided that I will add an option to config.cpp that lets you select what version of the API to use (2.5 or 3.0). I will add instructions similar to the one provided by Uwe Jacobs here for those using v3.0: https://wordpress.org/support/topic/401-api-error-in-owm-weather/page/2/

> Here is the reply from OpenWeather Support:
> 
>     One Call 1.0 (2.5 syntaxes) is deprecated for all new free and startup users. All old users will have access to One Call 1.0, but new users can only get this access by subscribing to the Developer Plan. Thus, for all users, we recommend switching to the updated One Call 3.0, an updated version of One Call.
> 
> Here’s the description on how to subscribe and avoid any credit card changes:
> 
>     Go to https://home.openweathermap.org/subscriptions/billing_info/onecall_30/base?key=base&service=onecall_30
>     Follow the instructions to complete the subscription.
>     Go to https://home.openweathermap.org/subscriptions and set the “Calls per day (no more than)” to 1,000. This ensures you will never overrun the free calls.
> 
> Without the subscription, the following OWM Weather data is not available: Hourly Forecast, Daily Forecast, Alerts, Moonrise/set, Dew Point, UV Index, and GTAG.

**Comment by lmarzen** [comment]
@Dozentz I have added a new line to the config so you can select to use the One Call 3.0 API. I have also added further clarifications to the end of the README.

**Comment by lmarzen** [comment]
5af2047facaff09234bacca425487d5b3cc54e51 I fixed the case where 0's show for all fields when the One Call fails, but the Air Pollution API call succeeds. I also improved the error messages that will print to the display in the case that any API call fails. (now gives the HTTP status code)

**Comment by Dozentz** [comment]
Great, everything works. How to add Cyrillic support in a font? Does freesans support by default cyrillic.
