### ISSUE TITLE
The Red/Black/White e-paper is only visible while refreshing

### ISSUE THREAD

**Issue by K20shores** [lmarzen/esp32-weather-epd#52]
I have everything connected. When the controller refreshes the screen, I see a white background with the black text briefly, and then the display goes dark. The information is written on the screen, but it's like there is a nearly opaque darkish-red color on the screen. I've tried to include some pictures.

Any ideas on what might be going on?

White refresh:
![white-refresh](https://github.com/lmarzen/esp32-weather-epd/assets/13836216/08b90f19-83c1-4294-aa80-d74865da26d1)

Red-ish-dark-ish opaqueness:
![nearly_opaque](https://github.com/lmarzen/esp32-weather-epd/assets/13836216/12c0646f-a598-48fd-95fb-3d307a55174f)

**Comment by K20shores** [comment]
Never mind. You already covered this. I had to uncomment `DISP_3C_B` in config.h, of course.

However, it does seem to flash quite a bit, as if it's refreshing several times per second before it stabilizes. Not sure if that's expected or not

**Comment by lmarzen** [comment]
Glad you were able to get it figured out. And yes that is the expected behavior. The waveshare color papers require quite a bit of 'flashing' to refresh.
