### ISSUE TITLE
Humidity in Graph

### ISSUE THREAD

**Issue by Ianszh** [lmarzen/esp32-weather-epd#56]
I now have the correct Paper and everything works fine except, the humidity doesn't seem to be displayed in the graph.
No blocks appear even though I have a Humidity of 43%

**Comment by lmarzen** [comment]
Glad to hear everything is working. The graph displays temperature and percent of precipitation(PoP), not humidity.

**Comment by Ianszh** [comment]
Aha I see, thanks.
