### ISSUE TITLE
One Call API 3.0

### ISSUE THREAD

**Issue by diettelo** [lmarzen/esp32-weather-epd#61]
Hello,

i need some help with your Weather Station Project.

This is my Api Key and i also signed to 3.0, everything working:
https://api.openweathermap.org/data/3.0/onecall?lat=47.28&lon=12.83&units=metric&lang=de&appid=e186e663cc7f8efc0006a3129edabc25

but when i compile everything and upload my Firmware, Allway One Call 3.0 API -1: connection refused.

Here comes the funny part:

In my router it i can see an Ip Adress also give it a free Static IP via Mac Adress.
I can Ping that Adress but Target host not avaible.

I can send you my Code if you whant to take a look.
I have no clue what is wrong.

I also tried to change to 2.5 API Link and Version, nothing.

best regards,

diettelo
![Screenshot 2023-10-23 200021](https://github.com/lmarzen/esp32-weather-epd/assets/34889239/aea2b148-79cf-4af6-81fe-ab121fb11163)
![Screenshot 2023-10-23 200056](https://github.com/lmarzen/esp32-weather-epd/assets/34889239/5558b2a7-0c61-470f-b0ab-92bcb2d1d1b7)
![Screenshot 2023-10-23 200114](https://github.com/lmarzen/esp32-weather-epd/assets/34889239/cf5e69e3-122f-493e-b437-6811a8dffd50)
![Screenshot 2023-10-23 200134](https://github.com/lmarzen/esp32-weather-epd/assets/34889239/dcee5dd7-9dbd-4049-a07b-f53a99542c24)
![Screenshot 2023-10-23 200143](https://github.com/lmarzen/esp32-weather-epd/assets/34889239/3821e18d-28fb-4c9b-95a9-1a3ad8d486e5)
![Screenshot 2023-10-23 200150](https://github.com/lmarzen/esp32-weather-epd/assets/34889239/99757885-6dcb-48b0-b83f-672b0a07f19d)

**Comment by lmarzen** [comment]
Use the default endpoint.

**Comment by diettelo** [comment]
Sorry, can you show me a little bit more.
What Endpoind do you mean?

Have you an example?

**Comment by lmarzen** [comment]
Revert your OWM_ENDPOINT setting back to "api.openweathermap.org". This setting is here because some paid tiers have special endpoints, but usually the endpoint is just "api.openweathermap.org".

**Comment by diettelo** [comment]
Sorry, can you show me a little bit more.
What Endpoind do you mean?

Have you an example?
    

edit:

i try it, thx.

**Comment by lmarzen** [comment]
The code will construct the entire request based on your settings, so no need to specify https://api.openweathermap.org/data/3.0/onecall?lat=47.28&lon=12.83&units=metric&lang=de&....

Also if "e186e663cc7f8efc0006a3129edabc25" is your real api key you just leaked it. If this is the case, go to your openweathermap account to generate a new one and delete the old one.

**Comment by diettelo** [comment]
Thx, i will change that.

**Comment by diettelo** [comment]
Thanks for your Support.
It is running very fine.

The only Thing i wanted to know is:
Can the Small Clock larger be displayed and Postion Upper Left, where the Rain Symbol is?

**Comment by lmarzen** [comment]
There isn't a setting for that, but you could do that, by changing the position of where elements are drawn in renderer.cpp.

**Comment by diettelo** [comment]
Ok Thanks, I´ll check it out.

Is there a way to Support your work?

**Comment by lmarzen** [comment]
Are you asking to support the project with contributions, donating hardware, financially?
All are welcome and would be greatly appreciated. If you wanted to support the project with a donation I could setup the github sponsorships for this repo. I started this project for fun and I am glad that people are taking interest like yourself and want to support the project.
