### ISSUE TITLE
3D model of wooden case

### ISSUE THREAD

**Issue by Spanholz** [lmarzen/esp32-weather-epd#67]
Hi Luke,

I really liked your wooden case but wanted to 3D print it. I made a remodel and uploaded it to Printables. 
Hope you like it. 

https://www.printables.com/model/657756-case-for-esp32-weather-station

**Comment by lmarzen** [comment]
Hey Sven,

Sorry for the delayed response. I just wanted to say good work and that I will be linking to your design in the project readme!

Thanks for sharing your design!
