### ISSUE TITLE
Waveshare e-paper driver hat v.2.2 - different wiring

### ISSUE THREAD

**Issue by martinriegel** [lmarzen/esp32-weather-epd#71]
Hi. 
I got a Waveshare e-paper driver hat v.2.2 with my 7.5 e-paper hat (B) display.

I had to wire the VCC to the 3V3 pin on the ESP to get the display up and running. So maybe add that as an example to the wiring guide. 
![bilde](https://github.com/lmarzen/esp32-weather-epd/assets/20671115/aff21d32-8435-475c-87df-f6945d554cd1)

**Comment by PaekHyun** [comment]
i think you can change display config.
how about display config change to "A"

**Comment by lmarzen** [comment]
@martinriegel
Thanks for sharing I may add this.


@PaekHyun 
You can, and it may work however, you may lose some contrast or notice some graininess/noise, especially around the border.

Additionally, waveshare ([waveshare-driver-hat](https://www.waveshare.com/wiki/E-Paper_Driver_HAT)) and good-display ([despi-c02](https://v4.cecdn.yun300.cn/100001_1909185148/DESPI-C02%20Connector%20Board%20for%20E-paper%20Display%20V1.1.pdf)) indicate that the displays used by this project should be set to .47R (B). I saw some artifacting myself when setting it to 3R (A) so I wouldn't recomment this.
