### ISSUE TITLE
Can it work on a larger E-ink display?

### ISSUE THREAD

**Issue by vitality82** [lmarzen/esp32-weather-epd#72]
The use case would be hanging the panel on a wall, with a custom wooden frame, which doesn't make sense for a small display. Refresh would be once a day and I assume the sensor for indoor data can be excluded (as well from the interface) ?

**Comment by lmarzen** [comment]
Unfortunately, only the displays listed in the readme are currently supported. Support could be added for a larger panel, but significant effort would be required to scale and position icons and text appropriately.

**Comment by vitality82** [comment]
Thanks Luke!
