### ISSUE TITLE
esp32-weather-epd mod - download png from local http and view it

### ISSUE THREAD

**Issue by nicoh88** [lmarzen/esp32-weather-epd#74]
Hi Luke,

cool project. Thanks for sharing. I once did something similar with Kindle: https://github.com/nicoh88/kindle-kt3_weatherdisplay_battery-optimized

Unfortunately, the Kindle batteries only last 4 weeks, even after a battery swap. That's why I'm very interested in your project and would love to realise it.

However, I don't want to install sensors or anything similar. I would also like to continue to generate my image on my server - as I have all the data I need from the weather stations and Netatmo in ioBroker.

I am not a programmer, but as I understand the main.cpp, I would have to comment out the `drawCurrentConditions`, `drawForecast`, `drawLocationDate` and `drawOutlookGraph`. Specify the URL to the PNG at this point and then show it on the display.

Is this fundamentally problematic? Or is it really easy? Is there anything else I need to consider? 

I would return the battery level and Wifi quality to my server via API. In my shell script, I do this via cURL - it's simply an HTTP. Surely this also works with CPP?

Greetings Nico

**Comment by lmarzen** [comment]
Hi Nico,

Cool project, you've got going on. 

Sounds relatively straightforward to receive an image and display it. You are on the right track and correctly identified the functions you will need to remove.

Good luck with your modifications.

-Luke

**Comment by nicoh88** [comment]
@lmarzen 

My order is on its way and will arrive in the next few days. I've already created a fork and am playing around.

Would you provide me with the source file for the wiring diagrams? Then I can adapt it in my fork for the e-Paper HAT rev2.3.

Thank you

**Comment by nicoh88** [comment]
@lmarzen 

I'm done. Here my GitHub: https://github.com/nicoh88/esp32-weather-epd_display-http-bitmap-bin

Thanks for your initial code and inspiration!

**Comment by lmarzen** [comment]
Wow! Incredible work!

**Comment by lmarzen** [comment]
Oh, this is an interesting observation. Great attention to detail.

> I have not connected the display GDEY075T7 with the DESPI-C02 to the GPIO pin D3 / 26 - because the display has a delay of approx. 1.5 seconds after which the power supply is active before it can be initialized. That's why I connected 3.3V from DESPI-C02 directly to 3V3 of the FireBeetle.
