### ISSUE TITLE
Change hourly forecast diagram

### ISSUE THREAD

**Issue by miloit** [lmarzen/esp32-weather-epd#75]
Hello,

is it possible to decide if the hourly forecast diagram can be changed also to a weekly forcast diagramm?

**Comment by lmarzen** [comment]
Unfortunately, Open Weather Map's OneCall API https://openweathermap.org/api/one-call-3 does not provide weekly weather information and only provides daily weather forecasts for 8 days out.

**Comment by miloit** [comment]
Okay thank you....and a history function?

**Comment by lmarzen** [comment]
Can you please elaborate?

**Comment by lmarzen** [comment]
Closed since this issue is inactive.
