### ISSUE TITLE
Adding locales Ukraine and air purity IAQ?

### ISSUE THREAD

**Issue by onatskiy-sergey** [lmarzen/esp32-weather-epd#76]
Is it possible to add the system language Ukraine. Well, and all other settings including air purity?

**Comment by lmarzen** [comment]
Yes this is definitely possible. To add a new language you need to copy the english locale file in platformio/src/locales. Then translate the file. Be sure to read comments in the file, they have helpful information.

To add a new air quality scale isn't hard either. I can do this for you if you can link me to the gov.ua page that defines Ukraine's air quality scale.

**Comment by lmarzen** [comment]
Closed since this issue is inactive.
