### ISSUE TITLE
Adding new display items and edit icons 5 days

### ISSUE THREAD

**Issue by Dozentz** [lmarzen/esp32-weather-epd#8]
Tell me how to add a new monitoring item as "Daylength"
And also how to make a gray frame behind the weather icon for 5 days. I tried to increase the size of the icons for 5 days, but the icon turned out blurry.
`    // icons
    display.drawInvertedBitmap(x, 350 + 69 / 2 - 32 - 6,
                               getForecastBitmap64(daily[i]),
                               64, 64, GxEPD_BLACK);`
I change it to 96 and the icons are blurry
`    // icons
    display.drawInvertedBitmap(x, 350 + 69 / 2 - 32 - 6,
                               getForecastBitmap64(daily[i]),
                               96, 96, GxEPD_BLACK);`

**Comment by lmarzen** [comment]
Some epaper screens support gray scale, but this display does not. from the product page... Display color: black, white. Grey scale: 2.  (https://www.waveshare.com/product/7.5inch-e-paper-hat.htm)

To create gradients, you can use various checkboard patterns. I used this technique for my outlook graph to draw the probability of precipitation bars in gray. You could achieve this in effect by either adding the effect to the icons manually(probably a lot of work) or alternatively; I would suggest you create a function that will draw that effect over an area. The effect would be relatively simple to implement with nested for loops.
Something like this:

```
for (int x = x_start + (x_start % 2); x < x_end; x += 2)
{
  for (int y = y_start + (y_start % 2); y < y_end; y += 2)
  {
    display.drawPixel(x, y, GxEPD_BLACK);
  }
}
```

As far as adding another monitoring item, I have added everything from the open weather map One Call 3.0 api to a series of data structures, (owm_current_t, owm_hourly_t, owm_daily_t, owm_alerts_t). If you look at some of the existing code in renderer.cpp you can see how these are used. api_response.h might also be useful as it contains the definitions of these data structures. See https://openweathermap.org/api/one-call-3 for what information you can get from this API call. I didn't see anything for day length but you could do some simple math to get this by finding the difference between sunrise and sunset.

Your issue with increasing the size of the Icon is that you are trying to render the 64x64 version (getForecastBitmap**64**(daily[i])) of the icon at 96x96. You should edit getForecastBitmap**64**(daily[i]) (and probably rename it to 96) by finding and replacing _64x64 with _96x96 in that function. for example wi_day_thunderstorm_64x64 should become wi_day_thunderstorm_96x96. Also be sure to #include "icons/icons_96x96.h".
