### ISSUE TITLE
e-paper display palely

### ISSUE THREAD

**Issue by Mor1arty** [lmarzen/esp32-weather-epd#82]
Hello!

I'm using waveshare E-Paper_ESP32_Driver_Board with 7.5 inch e-Paper (V2).

I think my configurations are right as the e-Paper did display contents.

However, when the driver board restarted, the e-Paper faded in and out. After that, the e-Paper remained in pale pictures and words, which could be hardly seen without strong light.

I've tried the official display demo project, and the e-Paper could show everything normally.

Could you please help me fix it?

![2141708069407_ pic_hd](https://github.com/lmarzen/esp32-weather-epd/assets/56692142/aeece1c0-c94d-44f8-b013-a1ac8d4ee4d6)

![e27e13a4c61c25c3408fc41c039ccc18](https://github.com/lmarzen/esp32-weather-epd/assets/56692142/72d7b1f6-32d9-47e2-ac7c-5038b55e7428)

**Comment by Mor1arty** [comment]
Thanks for your help!

I'm using waveshare esp32 e-Paper Driver Board isntead of firebeetle esp32-e board.

I reset all my configurations and tighten the wires, then my problem fixed!

Thanks again!

**Comment by lmarzen** [comment]
Try setting your switch to 0.47R (A).

**Comment by Mor1arty** [comment]
> Try setting your switch to 0.47R (A).
> 
> It seems that for the driver hat, 0.47R is B, but on the esp32 waveshare board 0.47R is A?

Yes exactly!

The e-Paper works perfectly after I turn the switch on the esp32 waveshare board from B( by default) to A.

Thank you! You are so cool!

**Comment by lmarzen** [comment]
Glad to hear that was it!
