### ISSUE TITLE
e-paper driver HAT 2.2 vs. 2.3

### ISSUE THREAD

**Issue by Nykaer** [lmarzen/esp32-weather-epd#91]
Having an issue with the e-paper not doing anything at all.  

Found that the HAT is rev. 2.3, and there seem to be some changes to pins
https://www.waveshare.com/wiki/E-Paper_Driver_HAT

"RST pin now is for reset control, and not for power on/off".    

Could that be an issue??

**Comment by lmarzen** [comment]
Yes. This project does not currently support the waveshare hat rev2.3.

**Comment by Nykaer** [comment]
Thought as much..   Seems odd, that a breaking change does not bump the rev. number to at least 3.0.

**Comment by lmarzen** [comment]
Yeah, same. Some people have got the rev2.3 working with this project using various work arounds. If you're curious, search the other issues on this github page. I personally don't own a rev2.3 board and haven't bothered ordering one just to debug it. The despi-c02 is a better option for low power applications, so I recommend that instead.

**Comment by ltwin8** [comment]
see #199
