### ISSUE TITLE
3D Printed Enclosure Contribution

### ISSUE THREAD

**Issue by TheMeanCanEHdian** [lmarzen/esp32-weather-epd#93]
Hello,

Below is the link and some images for a 3D enclosure I designed for this project. Thank you for creating this in the first place!
https://www.printables.com/model/841458-weather-display-enclosure

![20240412_083223](https://github.com/lmarzen/esp32-weather-epd/assets/16025103/b2c5efa8-bfab-40a0-bc0b-380106dcb79e)
![20240412_083431](https://github.com/lmarzen/esp32-weather-epd/assets/16025103/20147e88-9531-40c7-a2b1-a7682d87b78a)
![20240412_083249](https://github.com/lmarzen/esp32-weather-epd/assets/16025103/d8c71568-7fc3-4a23-9dd7-643038b1f582)
![20240412_075808](https://github.com/lmarzen/esp32-weather-epd/assets/16025103/aa3173bf-5913-4a72-b0a6-3c94bc5de0b7)
![20240412_082855](https://github.com/lmarzen/esp32-weather-epd/assets/16025103/3efd7794-8f8b-4133-b55b-4c215eb9d9f0)

**Comment by lmarzen** [comment]
Wow, that's a nice design. Your project turned out very nicely. I added a link to the project readme. Thank you for sharing!
