### ISSUE TITLE
Washed out display after refresh

### ISSUE THREAD

**Issue by TheMeanCanEHdian** [lmarzen/esp32-weather-epd#95]
Today I noticed a new problem where the display is washed out and splotchy over a certain vertical threshold. I was wondering if you had any thoughts on what might be causing this outside of a hardware issue. Below are an image showing the issue and a video showing the refresh process (after a reset).

The display looks sharp while refreshing, so I am not sure what might be the issue.

![20240416_115508](https://github.com/lmarzen/esp32-weather-epd/assets/16025103/32a1dd59-42db-46ea-acd6-5c807958f09d)

https://github.com/lmarzen/esp32-weather-epd/assets/16025103/c0df2252-cd29-479f-b8dc-800b93110626

**Comment by TheMeanCanEHdian** [comment]
I also tried the following with no change:
- Reseating the display cables and connectors
- Removing and reconnecting the battery
- Powering with USB and battery connected
- Powering with only USB connected

**Comment by lmarzen** [comment]
What driver board are you using (Waveshare Rev2.2/2.3 or DESPI-CO2)? Make sure the switch(es) are set as specified in the README.

**Comment by TheMeanCanEHdian** [comment]
The switch was set as specified (when I move it to the other position it is way worse) but when I moved it back it now seems good? Perhaps the switch was slightly loose. It's all locked in my enclosure so not sure what would have happened but it's looking good!

Perhaps this will help someone in the future. Thanks!

**Comment by lmarzen** [comment]
Interesting. Thanks for responding with your fix. I didn't even think that the switch might not be all the way set in position. This may help others with similar issues.

**Comment by ayh20** [comment]
FWIW - I came here to find the link to buy a new panel as mine had become "faded" after working just fine for the last year or so.  Just thought i'd search the posts to see if anyone else had had any failures and saw this post.

Did the the same as OP. Flipped the Display config switch, reset and the screen is dark... flipped it back and reset, screen is displaying again correctly !

Hope this helps someone else
