### ISSUE TITLE
May I ask what software is used to produce your simulation pictures?

### ISSUE THREAD

**Issue by FerrymanAnn** [lmarzen/esp32-weather-epd#97]
As mentioned in the title, I am a beginner and I would like to know what software can be used to draw simulations like yours,Thank you.
![mmexport1713861481948](https://github.com/lmarzen/esp32-weather-epd/assets/74294695/8f20b4c1-5356-4cb5-8a5c-44a506a6e260)

**Comment by lmarzen** [comment]
I used gimp to make that wiring diagram. gimp is just a general-purpose photo editing tool. There are many purpose built tools for making wiring schematics, and a quick google for "wiring schematic software" will bring up a bunch of discussions about available software.

**Comment by FerrymanAnn** [comment]
> I used gimp to make that wiring diagram. gimp is a free and open-source general-purpose photo editing tool. There are many purpose built tools for making wiring schematics, and a quick google for "wiring schematic software" will bring up a bunch of discussions about available software.

Thank you for your reply. I will continue to study
